import { IconType } from 'react-icons';
import {
  FiWifi,
  FiTruck,
  FiZap,
  FiSun,
  FiCoffee,
  FiFeather,
  FiAirplay,
  FiThermometer,
  FiBox,
  FiAnchor,
  FiDroplet,
  FiMapPin,
  FiSunrise,
  FiBatteryCharging,
  FiMusic,
  FiHeadphones,
  FiFramer,
  FiFilm,
  FiTv,
  FiMonitor,
  FiLock,
  FiHome,
  FiCamera,
  FiTool,
} from 'react-icons/fi';

export type Amenity = {
  name: string;
  icon: IconType;
  selected: boolean;
};

export const amenities: Amenity[] = [
  { name: 'wi-fi', icon: FiWifi, selected: false },
  { name: 'parking', icon: FiTruck, selected: false },
  { name: 'fire pit', icon: FiZap, selected: false },
  { name: 'bbq grill', icon: FiSun, selected: false },
  { name: 'outdoor furniture', icon: FiMapPin, selected: false },
  { name: 'private bathroom', icon: FiCoffee, selected: false },
  { name: 'hot shower', icon: FiFeather, selected: false },
  { name: 'kitchenette', icon: FiAirplay, selected: false },
  { name: 'heating', icon: FiThermometer, selected: false },
  { name: 'air conditioning', icon: FiBox, selected: false },
  { name: 'bed linens', icon: FiAnchor, selected: false },
  { name: 'towels', icon: FiDroplet, selected: false },
  { name: 'balcony or terrace', icon: FiSunrise, selected: false },
  { name: 'solar power', icon: FiBatteryCharging, selected: false },
  { name: 'sound system', icon: FiMusic, selected: false },
  { name: 'kitchen utensils', icon: FiTool, selected: false },
  { name: 'refrigerator', icon: FiFramer, selected: false },
  { name: 'lanterns', icon: FiFilm, selected: false },
  { name: 'first aid kit', icon: FiTv, selected: false },
  { name: 'tv', icon: FiMonitor, selected: false },
  { name: 'security system', icon: FiLock, selected: false },
  { name: 'self check-in', icon: FiHome, selected: false },
  { name: 'security cameras', icon: FiCamera, selected: false },
];

export const conservativeAmenities: Amenity[] = [
  { name: 'wi-fi', icon: FiWifi, selected: false },
  { name: 'parking', icon: FiTruck, selected: false },
  { name: 'fire pit', icon: FiZap, selected: false },
  { name: 'bbq grill', icon: FiSun, selected: false },
  { name: 'outdoor furniture', icon: FiMapPin, selected: false },
  { name: 'private bathroom', icon: FiCoffee, selected: false },
  { name: 'hot shower', icon: FiFeather, selected: false },
  { name: 'kitchenette', icon: FiAirplay, selected: false },
  { name: 'heating', icon: FiThermometer, selected: false },
  { name: 'air conditioning', icon: FiBox, selected: false },
  { name: 'bed linens', icon: FiAnchor, selected: false },
  { name: 'towels', icon: FiDroplet, selected: false },
  { name: 'balcony', icon: FiSunrise, selected: false },
  { name: 'solar power', icon: FiBatteryCharging, selected: false },
  { name: 'sound system', icon: FiMusic, selected: false },
  { name: 'kitchen utensils', icon: FiHeadphones, selected: false },
  { name: 'refrigerator', icon: FiFramer, selected: false },
  { name: 'lanterns', icon: FiFilm, selected: false },
  { name: 'first aid kit', icon: FiTv, selected: false },
  { name: 'tv', icon: FiMonitor, selected: false },
  { name: 'security system', icon: FiLock, selected: false },
  { name: 'self check-in', icon: FiHome, selected: false },
  { name: 'security cameras', icon: FiCamera, selected: false },
];
